# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'windows-latest'
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/complaint.Test/Dockerfile'
        buildContext: '$(Build.Repository.LocalPath)'
        tags: |
          $(tag)
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/complaint_API/Dockerfile'
        buildContext: '$(Build.Repository.LocalPath)'
        tags: |
          $(tag)
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/identity.test/Dockerfile'
        buildContext: '$(Build.Repository.LocalPath)'
        tags: |
          $(tag)
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Identity.API/Dockerfile'
        buildContext: '$(Build.Repository.LocalPath)'
        tags: |
          $(tag)
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/complaint_gateway.api/Dockerfile'
        buildContext: '$(Build.Repository.LocalPath)'
        tags: |
          $(tag)
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/gateway.test/Dockerfile'
        buildContext: '$(Build.Repository.LocalPath)'
        tags: |
          $(tag)
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/IdentityServer/Dockerfile'
        buildContext: '$(Build.Repository.LocalPath)'
        tags: |
          $(tag)