version: '3.4'

services:
  complaint_gateway.api:
    image: ${DOCKER_REGISTRY-}complaintgatewayapi
    build:
      context: .
      dockerfile: complaint_gateway.APi\Dockerfile

  gateway.test:
    image: ${DOCKER_REGISTRY-}gatewaytest
    build:
      context: .
      dockerfile: gateway.Test\Dockerfile


  identityserver:
    image: ${DOCKER_REGISTRY-}identityserver
    build:
      context: .
      dockerfile: IdentityServer\Dockerfile


  identity.test:
    image: ${DOCKER_REGISTRY-}identitytest
    build:
      context: .
      dockerfile: identity.test\Dockerfile

